AllCops:
  Exclude:
    - "**/*.haml"
  TargetRubyVersion: 3.2
  NewCops: enable

Lint/EmptyFile:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

require: rubocop-rspec


